name: Release base - Build and publish build_fleet image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'

jobs:
  build-publish-amd64:
    runs-on: ubuntu-latest
    steps:
      - run: |
          rm -rf manifests
          git clone https://github.com/neuvector/manifests
          cd manifests
          git checkout ${{ github.event.inputs.branch }}

          cd build/amd64
          make build_fleet
                    
          docker login -u nvbuild -p "${{ secrets.DOCKERHUB_NVBUILD_PASSWORD }}"
          docker tag neuvector/build_fleet:latest neuvector/build_fleet:amd64.latest
          docker push neuvector/build_fleet:amd64.latest
          docker tag neuvector/build_fleet:v1 neuvector/build_fleet:amd64.v1
          docker push neuvector/build_fleet:amd64.v1
          docker tag neuvector/build_fleet:v2 neuvector/build_fleet:amd64.v2
          docker push neuvector/build_fleet:amd64.v2
          docker tag neuvector/build_fleet:v3 neuvector/build_fleet:amd64.v3
          docker push neuvector/build_fleet:amd64.v3
          docker logout

  build-publish-arm64:
    runs-on: hosted-ubuntu-arm64-build-server 
    steps:
      - run: |
          rm -rf manifests
          git clone https://github.com/neuvector/manifests
          cd manifests
          git checkout ${{ github.event.inputs.branch }}

          cd build/arm64
          make build_fleet

          docker login -u nvbuild -p "${{ secrets.DOCKERHUB_NVBUILD_PASSWORD }}"
          docker tag neuvector/build_fleet:latest neuvector/build_fleet:arm64.latest
          docker push neuvector/build_fleet:arm64.latest
          docker tag neuvector/build_fleet:v1 neuvector/build_fleet:arm64.v1
          docker push neuvector/build_fleet:arm64.v1
          docker tag neuvector/build_fleet:v2 neuvector/build_fleet:arm64.v2
          docker push neuvector/build_fleet:arm64.v2
          docker tag neuvector/build_fleet:v3 neuvector/build_fleet:arm64.v3
          docker push neuvector/build_fleet:arm64.v3
          docker logout

  build-publish-multi-arch:
    runs-on: ubuntu-latest
    needs: [build-publish-amd64, build-publish-arm64]
    steps:
      - run: |
          docker login -u nvbuild -p "${{ secrets.DOCKERHUB_NVBUILD_PASSWORD }}"

          docker manifest create neuvector/build_fleet:latest \
              neuvector/build_fleet:amd64.latest \
              neuvector/build_fleet:arm64.latest
          docker manifest push neuvector/build_fleet:latest

          docker manifest create neuvector/build_fleet:v1 \
              neuvector/build_fleet:amd64.v1 \
              neuvector/build_fleet:arm64.v1
          docker manifest push neuvector/build_fleet:v1

          docker manifest create neuvector/build_fleet:v2 \
              neuvector/build_fleet:amd64.v2 \
              neuvector/build_fleet:arm64.v2
          docker manifest push neuvector/build_fleet:v2

          docker manifest create neuvector/build_fleet:v3 \
              neuvector/build_fleet:amd64.v3 \
              neuvector/build_fleet:arm64.v3
          docker manifest push neuvector/build_fleet:v3
          
          docker logout
